-- Little One Store: schema + security + seed
create table if not exists public.products (
  id text primary key,
  sort int not null default 100,
  category text not null,
  price_czk numeric not null,
  old_price_czk numeric,
  rating numeric not null default 4.8,
  reviews int not null default 0,
  emoji text not null default '🧸',
  gradient text,
  sizes jsonb not null default '[]',
  ages jsonb not null default '[]',
  colors jsonb not null default '[]',
  badge text,
  featured boolean not null default false,
  best_seller boolean not null default false,
  seasonal boolean not null default false,
  is_new boolean not null default false,
  hidden boolean not null default false,
  in_stock boolean not null default true,
  name_cs text, name_en text, name_uk text,
  desc_cs text, desc_en text, desc_uk text,
  material_cs text, material_en text, material_uk text,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null
);

alter table public.products enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "public read visible products" on public.products;
create policy "public read visible products" on public.products
  for select using (hidden = false or auth.role() = 'authenticated');

drop policy if exists "admin write products" on public.products;
create policy "admin write products" on public.products
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists "public read settings" on public.site_settings;
create policy "public read settings" on public.site_settings
  for select using (true);

drop policy if exists "admin write settings" on public.site_settings;
create policy "admin write settings" on public.site_settings
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into public.site_settings (key, value)
  values ('shipping', '{"shipping_czk": 90, "free_over_czk": 2000}')
  on conflict (key) do nothing;

insert into storage.buckets (id, name, public)
  values ('product-images', 'product-images', true)
  on conflict (id) do nothing;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

drop policy if exists "admin upload product images" on storage.objects;
create policy "admin upload product images" on storage.objects
  for insert with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

drop policy if exists "admin update product images" on storage.objects;
create policy "admin update product images" on storage.objects
  for update using (bucket_id = 'product-images' and auth.role() = 'authenticated');

drop policy if exists "admin delete product images" on storage.objects;
create policy "admin delete product images" on storage.objects
  for delete using (bucket_id = 'product-images' and auth.role() = 'authenticated');

insert into public.products
  (id, sort, category, price_czk, old_price_czk, rating, reviews, emoji, gradient,
   sizes, ages, colors, badge, featured, best_seller, seasonal, is_new, hidden, in_stock,
   name_cs, name_en, name_uk, desc_cs, desc_en, desc_uk, material_cs, material_en, material_uk)
values
('girls-summer-set', 10, 'girls', 349, null, 4.9, 41, '🎀', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Pink", "hex": "#f7a8c4", "images": ["/products/girls-summer-set/pink-1.jpg", "/products/girls-summer-set/pink-2.jpg", "/products/girls-summer-set/pink-3.jpg", "/products/girls-summer-set/pink-4.jpg", "/products/girls-summer-set/pink-5.jpg"]}, {"name": "Peach Pink", "hex": "#f5bfae", "images": ["/products/girls-summer-set/peachpink-1.jpg", "/products/girls-summer-set/peachpink-2.jpg", "/products/girls-summer-set/peachpink-3.jpg", "/products/girls-summer-set/peachpink-4.jpg", "/products/girls-summer-set/peachpink-5.jpg"]}, {"name": "Dark Pink", "hex": "#e0729a", "images": ["/products/girls-summer-set/darkpink-1.jpg", "/products/girls-summer-set/darkpink-2.jpg", "/products/girls-summer-set/darkpink-3.jpg", "/products/girls-summer-set/darkpink-4.jpg", "/products/girls-summer-set/darkpink-5.jpg"]}]'::jsonb, 'New', true, false, true, true, false, true, 'Dívčí letní set – tričko a šortky', 'Girls Summer Set – Tee & Shorts', 'Літній комплект для дівчинки – футболка та шорти', 'Lehký a pohodlný letní komplet ze 100% bavlny, který zajistí maximální komfort i během horkých dnů. Souprava obsahuje růžové tričko s ozdobnou aplikací mašle a pruhované šortky s pružným pasem. Ideální na procházky, hraní i každodenní nošení.', 'A light and comfy summer set in 100% cotton that keeps little ones cool on hot days. The set pairs a pink tee with a decorative bow appliqué and striped shorts with an elastic waist — perfect for walks, play and everyday wear.', 'Легкий і зручний літній комплект зі 100% бавовни, що забезпечує максимальний комфорт навіть у спекотні дні. До набору входить рожева футболка з декоративним бантиком і смугасті шорти з еластичним поясом. Ідеально для прогулянок, ігор і щоденного носіння.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('girls-flower-set', 20, 'girls', 329, null, 4.8, 32, '🌸', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Pink", "hex": "#f2b7c6", "images": ["/products/girls-flower-set/pink-1.jpg", "/products/girls-flower-set/pink-2.jpg", "/products/girls-flower-set/pink-3.jpg", "/products/girls-flower-set/pink-4.jpg", "/products/girls-flower-set/pink-5.jpg"]}]'::jsonb, null, true, false, false, false, false, true, 'Dívčí souprava – mikina a kalhoty', 'Girls Set – Sweatshirt & Pants', 'Комплект для дівчинки – світшот і штани', 'Elegantní a pohodlná souprava z 95 % bavlny a 5 % elastanu. Komplet tvoří mikina s dlouhým rukávem, ozdobným krajkovým límečkem a jemným květinovým vzorem spolu s pohodlnými kalhotami s pružným pasem. Měkká, příjemná na dotek a zároveň pružná.', 'An elegant, comfortable two-piece set in 95% cotton and 5% elastane. A long-sleeve top with a delicate lace collar and fine floral print comes with soft pants with an elastic waist — gentle to the touch with just the right stretch.', null, '95 % bavlna, 5 % elastan', '95% cotton, 5% elastane', '95 % бавовна, 5 % еластан'),
('bunny-3piece-set', 30, 'baby', 399, null, 4.9, 56, '🐰', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["9-12m", "12-18m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Beige", "hex": "#e6d3b8", "images": ["/products/bunny-3piece-set/beige-1.jpg", "/products/bunny-3piece-set/beige-2.jpg", "/products/bunny-3piece-set/beige-3.jpg", "/products/bunny-3piece-set/beige-4.jpg", "/products/bunny-3piece-set/beige-5.jpg"]}, {"name": "Pink", "hex": "#f4b9c8", "images": ["/products/bunny-3piece-set/pink-1.jpg", "/products/bunny-3piece-set/pink-2.jpg", "/products/bunny-3piece-set/pink-3.jpg", "/products/bunny-3piece-set/pink-4.jpg", "/products/bunny-3piece-set/pink-5.jpg"]}]'::jsonb, 'Bestseller', true, true, false, false, false, true, 'Dětská 3dílná souprava se zajíčkem', 'Bunny 3-Piece Set with Vest', 'Дитячий комплект із 3 частин із зайчиком', 'Stylová a pohodlná 3dílná souprava pro nejmenší, ideální na jaro, podzim i chladnější letní dny. Komplet obsahuje mikinu s roztomilým motivem zajíčka, pohodlné bavlněné kalhoty a lehce zateplenou vestu s kapucí. K dispozici v béžové a růžové barvě.', 'A stylish 3-piece set for the littlest ones — ideal for spring, autumn and cooler summer days. It includes a sweatshirt with an adorable bunny motif, soft cotton pants and a lightly insulated hooded vest. Available in beige and pink.', null, 'Mikina a kalhoty 100 % bavlna · vesta 50 % bavlna, 50 % polyester', 'Sweatshirt & pants 100% cotton · vest 50% cotton, 50% polyester', 'Світшот і штани 100 % бавовна · жилетка 50 % бавовна, 50 % поліестер'),
('cotton-pants-2pack', 40, 'baby', 199, null, 4.7, 63, '🦁', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["3-6m", "6-9m", "9-12m", "12-18m"]'::jsonb, '["0-6m", "6-12m", "12-24m"]'::jsonb, '[{"name": "Safari", "hex": "#d9c39a", "images": ["/products/cotton-pants-2pack/safari-1.jpg", "/products/cotton-pants-2pack/safari-2.jpg", "/products/cotton-pants-2pack/safari-3.jpg", "/products/cotton-pants-2pack/safari-4.jpg", "/products/cotton-pants-2pack/safari-5.jpg"]}]'::jsonb, null, false, true, false, false, false, true, 'Dětské bavlněné kalhoty – 2 ks', 'Cotton Baby Pants – 2-Pack', 'Дитячі бавовняні штани – 2 шт.', 'Pohodlné dětské kalhoty ze 100% bavlny pro každodenní nošení. Sada obsahuje 2 kusy – jedny s veselým motivem safari zvířátek a jedny jednobarevné s potiskem zebry. Díky pružnému pasu se snadno oblékají a perfektně padnou.', 'Comfy 100% cotton baby pants for all-day wear. The pack contains two pairs — one with a cheerful safari-animal print and one plain with a zebra motif. The elastic waist makes dressing quick and easy.', 'Зручні дитячі штани зі 100% бавовни для щоденного носіння. У наборі 2 штуки — одні з веселим сафарі-принтом, другі однотонні із зеброю. Завдяки еластичному поясу легко вдягаються та чудово сидять.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('bear-3piece-set', 50, 'boys', 399, null, 4.9, 48, '🐻', 'linear-gradient(140deg, #ddefff 0%, #c2ddff 60%, #aacdf5 100%)', '["6-9m", "9-12m", "12-18m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Blue", "hex": "#a9c8ea", "images": ["/products/bear-3piece-set/blue-1.jpg", "/products/bear-3piece-set/blue-2.jpg", "/products/bear-3piece-set/blue-3.jpg", "/products/bear-3piece-set/blue-4.jpg", "/products/bear-3piece-set/blue-5.jpg"]}, {"name": "Grey", "hex": "#b9bdc4", "images": ["/products/bear-3piece-set/grey-1.jpg", "/products/bear-3piece-set/grey-2.jpg", "/products/bear-3piece-set/grey-3.jpg", "/products/bear-3piece-set/grey-4.jpg", "/products/bear-3piece-set/grey-5.jpg"]}]'::jsonb, 'Bestseller', true, true, false, false, false, true, 'Chlapecká 3dílná souprava s medvídkem', 'Boys Bear 3-Piece Set', 'Комплект для хлопчика з ведмедиком (3 частини)', 'Pohodlná a stylová 3dílná souprava pro malé kluky, ideální na jaro, podzim i chladnější dny. Součástí kompletu je mikina s roztomilým motivem medvídka, pohodlné bavlněné kalhoty a lehce zateplená vesta s kapucí. K dispozici v modré a šedé barvě.', 'A comfortable, stylish 3-piece set for little boys — great for spring, autumn and chilly days. Includes a sweatshirt with a cute teddy-bear motif, soft cotton pants and a lightly insulated hooded vest. Available in blue and grey.', 'Зручний і стильний комплект із 3 частин для маленьких хлопчиків — чудовий для весни, осені та прохолодних днів. До набору входить світшот із милим ведмедиком, зручні бавовняні штани та легка утеплена жилетка з капюшоном. Доступний у блакитному та сірому кольорах.', 'Mikina a kalhoty 100 % bavlna · vesta 50 % bavlna, 50 % polyester', 'Sweatshirt & pants 100% cotton · vest 50% cotton, 50% polyester', 'Світшот і штани 100 % бавовна · жилетка 50 % бавовна, 50 % поліестер'),
('boys-vest-3piece', 60, 'boys', 399, null, 4.8, 37, '🦺', 'linear-gradient(140deg, #e2f5e4 0%, #cdeccd 60%, #b5e0b8 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Green", "hex": "#9fbf8f", "images": ["/products/boys-vest-3piece/green-1.jpg", "/products/boys-vest-3piece/green-2.jpg", "/products/boys-vest-3piece/green-3.jpg", "/products/boys-vest-3piece/green-4.jpg", "/products/boys-vest-3piece/green-5.jpg"]}, {"name": "Grey", "hex": "#b9bdc4", "images": ["/products/boys-vest-3piece/grey-1.jpg", "/products/boys-vest-3piece/grey-2.jpg", "/products/boys-vest-3piece/grey-3.jpg", "/products/boys-vest-3piece/grey-4.jpg", "/products/boys-vest-3piece/grey-5.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Chlapecká 3dílná souprava s vestou', 'Boys 3-Piece Set with Vest', 'Комплект для хлопчика з жилеткою (3 частини)', 'Moderní a pohodlná 3dílná souprava pro malé kluky, ideální na jaro, podzim i chladnější dny. Komplet obsahuje mikinu s dlouhým rukávem, pohodlné kalhoty a lehce zateplenou vestu s kapucí. Stylový design vhodný pro každodenní nošení.', 'A modern 3-piece set for little boys, ideal for spring, autumn and colder days. The set includes a long-sleeve sweatshirt, comfortable pants and a lightly insulated hooded vest in a stylish colourway made for everyday wear.', 'Сучасний і зручний комплект із 3 частин для маленьких хлопчиків, ідеальний для весни, осені та холодніших днів. До набору входить світшот із довгим рукавом, зручні штани та легка утеплена жилетка з капюшоном.', 'Mikina a kalhoty 100 % bavlna · vesta 50 % bavlna, 50 % polyester', 'Sweatshirt & pants 100% cotton · vest 50% cotton, 50% polyester', 'Світшот і штани 100 % бавовна · жилетка 50 % бавовна, 50 % поліестер'),
('boys-hoodie-3piece', 70, 'boys', 399, null, 4.8, 44, '🧢', 'linear-gradient(140deg, #ddefff 0%, #c2ddff 60%, #aacdf5 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Blue", "hex": "#a9c8ea", "images": ["/products/boys-hoodie-3piece/blue-1.jpg", "/products/boys-hoodie-3piece/blue-2.jpg", "/products/boys-hoodie-3piece/blue-3.jpg", "/products/boys-hoodie-3piece/blue-4.jpg", "/products/boys-hoodie-3piece/blue-5.jpg"]}, {"name": "Green", "hex": "#9fbf8f", "images": ["/products/boys-hoodie-3piece/green-1.jpg", "/products/boys-hoodie-3piece/green-2.jpg", "/products/boys-hoodie-3piece/green-3.jpg", "/products/boys-hoodie-3piece/green-4.jpg", "/products/boys-hoodie-3piece/green-5.jpg"]}]'::jsonb, null, true, false, false, false, false, true, 'Chlapecká 3dílná souprava s mikinou', 'Boys 3-Piece Hoodie Set', 'Комплект для хлопчика з худі (3 частини)', 'Stylová a pohodlná 3dílná souprava pro malé kluky, ideální pro každodenní nošení. Komplet obsahuje tričko s dlouhým rukávem, pohodlné kalhoty a mikinu na zip s kapucí. Moderní barvy a sportovní design z ní dělají skvělou volbu na procházky i hraní.', 'A stylish everyday 3-piece set for little boys: a long-sleeve tee, comfortable pants and a zip-up hoodie. The modern colours and sporty design make it a great choice for walks and playtime alike.', 'Стильний повсякденний комплект із 3 частин для маленьких хлопчиків: лонгслів, зручні штани та худі на блискавці з капюшоном. Сучасні кольори та спортивний дизайн — чудовий вибір для прогулянок та ігор.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('elephant-2piece-set', 80, 'boys', 289, null, 4.7, 29, '🐘', 'linear-gradient(140deg, #ddefff 0%, #c2ddff 60%, #aacdf5 100%)', '["6-9m", "9-12m", "12-18m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Blue", "hex": "#a9c8ea", "images": ["/products/elephant-2piece-set/blue-1.jpg", "/products/elephant-2piece-set/blue-2.jpg", "/products/elephant-2piece-set/blue-3.jpg", "/products/elephant-2piece-set/blue-4.jpg", "/products/elephant-2piece-set/blue-5.jpg"]}, {"name": "Grey", "hex": "#b9bdc4", "images": ["/products/elephant-2piece-set/grey-1.jpg", "/products/elephant-2piece-set/grey-2.jpg", "/products/elephant-2piece-set/grey-3.jpg", "/products/elephant-2piece-set/grey-4.jpg", "/products/elephant-2piece-set/grey-5.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Chlapecká souprava se sloníkem', 'Boys Elephant 2-Piece Set', 'Комплект для хлопчика зі слоником (2 частини)', 'Pohodlná a stylová 2dílná souprava pro malé kluky. Komplet obsahuje mikinu s dlouhým rukávem a roztomilou aplikací sloníka a pohodlné kalhoty s pružným pasem. Jemná modro-bílá barevná kombinace pro každodenní nošení.', 'A comfy two-piece set for little boys: a long-sleeve sweatshirt with an adorable elephant appliqué and soft pants with an elastic waist. The gentle blue-and-white palette keeps it fresh for every day.', null, '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('girls-love-3piece', 90, 'girls', 319, null, 4.9, 52, '💗', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Pink", "hex": "#f7a8c4", "images": ["/products/girls-love-3piece/pink-1.jpg", "/products/girls-love-3piece/pink-2.jpg", "/products/girls-love-3piece/pink-3.jpg", "/products/girls-love-3piece/pink-4.jpg", "/products/girls-love-3piece/pink-5.jpg"]}, {"name": "Dark Pink", "hex": "#e0729a", "images": ["/products/girls-love-3piece/darkpink-1.jpg", "/products/girls-love-3piece/darkpink-2.jpg", "/products/girls-love-3piece/darkpink-3.jpg", "/products/girls-love-3piece/darkpink-4.jpg", "/products/girls-love-3piece/darkpink-5.jpg"]}]'::jsonb, 'Bestseller', false, true, false, false, false, true, 'Dívčí 3dílná souprava Love', 'Girls Love 3-Piece Set', 'Комплект для дівчинки Love (3 частини)', 'Stylová a pohodlná 3dílná souprava pro malé slečny. Komplet obsahuje tričko s dlouhým rukávem, pohodlné kalhoty a mikinu na zip s kapucí. Romantický design se srdíčky a nápisem Love dodává soupravě roztomilý vzhled.', 'A sweet 3-piece set for little ladies: a long-sleeve tee, comfy pants and a zip-up hoodie. The romantic hearts-and-Love design gives the outfit an adorable look for every day.', 'Милий комплект із 3 частин для маленьких леді: лонгслів, зручні штани та худі на блискавці. Романтичний дизайн із сердечками та написом Love надає образу чарівності.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('girls-vest-3piece', 100, 'girls', 399, null, 4.8, 35, '🌷', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Pink", "hex": "#f2b7c6", "images": ["/products/girls-vest-3piece/pink-1.jpg", "/products/girls-vest-3piece/pink-2.jpg", "/products/girls-vest-3piece/pink-3.jpg", "/products/girls-vest-3piece/pink-4.jpg", "/products/girls-vest-3piece/pink-5.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Dívčí 3dílná souprava s vestou', 'Girls 3-Piece Set with Vest', 'Комплект для дівчинки з жилеткою (3 частини)', 'Elegantní a pohodlná 3dílná souprava pro malé slečny, ideální na jaro, podzim i chladnější dny. Komplet obsahuje mikinu s dlouhým rukávem, pohodlné kalhoty a lehce zateplenou vestu s kapucí. Jemná růžová barva se zlatými květinovými detaily.', 'An elegant 3-piece set for little ladies, ideal for spring, autumn and cooler days: a long-sleeve sweatshirt, comfortable pants and a lightly insulated hooded vest. Soft pink with golden floral details for a graceful look.', 'Елегантний комплект із 3 частин для маленьких леді, ідеальний для весни, осені та прохолодних днів: світшот із довгим рукавом, зручні штани та легка утеплена жилетка з капюшоном. Ніжний рожевий із золотистими квітковими деталями.', 'Mikina a kalhoty 100 % bavlna · vesta 50 % bavlna, 50 % polyester', 'Sweatshirt & pants 100% cotton · vest 50% cotton, 50% polyester', 'Світшот і штани 100 % бавовна · жилетка 50 % бавовна, 50 % поліестер'),
('boys-shirt-set', 110, 'boys', 359, null, 4.8, 26, '👔', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Script", "hex": "#d8cdbc", "images": ["/products/boys-shirt-set/script-1.jpg", "/products/boys-shirt-set/script-2.jpg", "/products/boys-shirt-set/script-3.jpg", "/products/boys-shirt-set/script-4.jpg", "/products/boys-shirt-set/script-5.jpg"]}, {"name": "Print", "hex": "#c8d4e6", "images": ["/products/boys-shirt-set/print-1.jpg", "/products/boys-shirt-set/print-2.jpg", "/products/boys-shirt-set/print-3.jpg", "/products/boys-shirt-set/print-4.jpg", "/products/boys-shirt-set/print-5.jpg"]}]'::jsonb, 'New', true, false, true, true, false, true, 'Chlapecký letní komplet – košile a šortky', 'Boys Summer Shirt Set', 'Літній комплект для хлопчика – сорочка та шорти', 'Elegantní letní 2dílný komplet pro malé kluky, ideální na rodinné oslavy, focení i běžné nošení. Souprava obsahuje stylovou košili s krátkým rukávem a pohodlné šortky s kapsami. Díky 100% bavlně je komplet lehký a prodyšný.', 'An elegant summer two-piece for little gentlemen — perfect for family celebrations, photo shoots and everyday wear. A short-sleeve shirt with an original print comes with comfy shorts with pockets, all in light, breathable cotton.', 'Елегантний літній комплект для маленьких джентльменів — ідеальний для родинних свят, фотосесій і щоденного носіння. Стильна сорочка з коротким рукавом та оригінальним принтом і зручні шорти з кишенями. Легка, дихаюча бавовна.', '100 % bavlna, lehká a prodyšná', '100% cotton, light and breathable', '100 % бавовна, легка та дихаюча'),
('boys-summer-set', 120, 'boys', 349, null, 4.7, 22, '☀️', 'linear-gradient(140deg, #ddefff 0%, #c2ddff 60%, #aacdf5 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Green", "hex": "#9fbf8f", "images": ["/products/boys-summer-set/green-1.jpg", "/products/boys-summer-set/green-2.jpg", "/products/boys-summer-set/green-3.jpg", "/products/boys-summer-set/green-4.jpg", "/products/boys-summer-set/green-5.jpg"]}, {"name": "Blue", "hex": "#a9c8ea", "images": ["/products/boys-summer-set/blue-1.jpg", "/products/boys-summer-set/blue-2.jpg", "/products/boys-summer-set/blue-3.jpg", "/products/boys-summer-set/blue-4.jpg"]}]'::jsonb, 'New', false, false, true, true, false, true, 'Chlapecký letní komplet – tričko a šortky', 'Boys Summer Tee Set', 'Літній комплект для хлопчика – футболка та шорти', 'Lehký a pohodlný 2dílný komplet pro malé kluky, ideální na teplé letní dny. Souprava obsahuje bavlněné tričko s krátkým rukávem a pohodlné šortky s pružným pasem. Elegantní kombinace bílé a barevných tónů.', 'A light two-piece summer set for little boys: a short-sleeve cotton tee and comfortable shorts with an elastic waist. A crisp white-and-colour combination for hot days, holidays and everyday wear.', 'Легкий комплект із 2 частин для маленьких хлопчиків на спекотні дні: бавовняна футболка з коротким рукавом і зручні шорти з еластичним поясом. Свіже поєднання білого з кольоровими акцентами.', '100 % bavlna, lehká a prodyšná', '100% cotton, light and breathable', '100 % бавовна, легка та дихаюча'),
('tropical-summer-set', 130, 'boys', 349, null, 4.8, 19, '🌴', 'linear-gradient(140deg, #e2f5e4 0%, #cdeccd 60%, #b5e0b8 100%)', '["9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Beige", "hex": "#e3d2b8", "images": ["/products/tropical-summer-set/beige-1.jpg", "/products/tropical-summer-set/beige-2.jpg", "/products/tropical-summer-set/beige-3.jpg", "/products/tropical-summer-set/beige-4.jpg", "/products/tropical-summer-set/beige-5.jpg"]}, {"name": "Green", "hex": "#9fbf8f", "images": ["/products/tropical-summer-set/green-1.jpg"]}]'::jsonb, 'New', false, false, true, true, false, true, 'Chlapecký letní komplet s tropickým vzorem', 'Tropical Summer Set', 'Літній комплект із тропічним принтом', 'Lehký a stylový 2dílný letní komplet pro malé kluky. Souprava obsahuje pohodlné tričko s krátkým rukávem a šortky s tropickým vzorem listů. Díky 100% bavlně je komplet příjemný na nošení a ideální do teplých letních dnů.', 'A light, stylish summer two-piece for little boys: a comfy short-sleeve tee and shorts with a tropical leaf print. Pure cotton keeps it soft, breathable and ready for hot summer days.', null, '100 % bavlna, lehká a prodyšná', '100% cotton, light and breathable', '100 % бавовна, легка та дихаюча'),
('boys-cotton-set', 140, 'boys', 329, null, 4.7, 17, '🤎', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["6-9m", "9-12m", "12-18m", "18-24m"]'::jsonb, '["6-12m", "12-24m"]'::jsonb, '[{"name": "Beige", "hex": "#e3d2b8", "images": ["/products/boys-cotton-set/beige-1.jpg", "/products/boys-cotton-set/beige-2.jpg", "/products/boys-cotton-set/beige-3.jpg"]}]'::jsonb, null, false, false, true, false, false, true, 'Chlapecká souprava – tričko a kalhoty', 'Boys Tee & Pants Set', 'Комплект для хлопчика – футболка та штани', 'Lehká a pohodlná 2dílná souprava pro malé kluky, ideální na teplejší dny. Komplet obsahuje tričko s krátkým rukávem a dlouhé kalhoty s pružným pasem v elegantní béžovo-hnědé kombinaci.', 'A light and comfortable two-piece set for warmer days: a short-sleeve tee and long pants with an elastic waist in an elegant beige-brown combination. Pure cotton makes it soft, breathable and great for every day.', 'Легкий і зручний комплект для теплих днів: футболка з коротким рукавом і довгі штани з еластичним поясом в елегантному бежево-коричневому поєднанні.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('girls-c-3piece', 150, 'girls', 349, null, 4.8, 24, '💖', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["0-3m", "3-6m", "6-9m", "9-12m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Pink", "hex": "#f7a8c4", "images": ["/products/girls-c-3piece/pink-1.jpg", "/products/girls-c-3piece/pink-2.jpg", "/products/girls-c-3piece/pink-3.jpg", "/products/girls-c-3piece/pink-4.jpg"]}, {"name": "Peach", "hex": "#f8c8b0", "images": ["/products/girls-c-3piece/peach-1.jpg", "/products/girls-c-3piece/peach-2.jpg", "/products/girls-c-3piece/peach-3.jpg", "/products/girls-c-3piece/peach-4.jpg", "/products/girls-c-3piece/peach-5.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Dívčí 3dílná souprava s písmenem C', 'Girls Letter-C 3-Piece Set', 'Комплект для дівчинки з літерою C (3 частини)', 'Stylová a pohodlná 3dílná souprava pro malé slečny. Komplet obsahuje tričko s dlouhým rukávem, pohodlné kalhoty a lehkou mikinu na patentky. Jemná růžová barva a moderní design s písmenem C dodávají sportovně-elegantní vzhled.', 'A stylish 3-piece set for little ladies: a long-sleeve tee, comfy pants and a light snap-button sweatshirt. Soft pink tones and a modern letter-C design give it a sporty-elegant look.', 'Стильний комплект із 3 частин для маленьких леді: лонгслів, зручні штани та легкий світшот на кнопках. Ніжний рожевий і сучасний дизайн із літерою C створюють спортивно-елегантний образ.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('girls-floral-3piece', 160, 'girls', 349, null, 4.9, 21, '🌼', 'linear-gradient(140deg, #ffeadd 0%, #ffd8c2 60%, #ffc9ad 100%)', '["0-3m", "3-6m", "6-9m", "9-12m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Peach", "hex": "#f8c8b0", "images": ["/products/girls-floral-3piece/peach-1.jpg"]}]'::jsonb, null, true, false, false, false, false, true, 'Dívčí 3dílná souprava s květinami', 'Girls Floral 3-Piece Set', 'Квітковий комплект для дівчинки (3 частини)', 'Roztomilá a pohodlná 3dílná souprava pro malé princezny. Komplet obsahuje body s dlouhým rukávem, pohodlné kalhoty a mikinu s kapucí. Jemná broskvová barva v kombinaci s květinovým motivem vytváří něžný a elegantní vzhled.', 'An adorable 3-piece set for little princesses: a long-sleeve bodysuit, comfy pants and a hooded sweatshirt. The gentle peach tone and floral motif create a tender, elegant look — lovely as a gift too.', 'Чарівний комплект із 3 частин для маленьких принцес: боді з довгим рукавом, зручні штани та худі з капюшоном. Ніжний персиковий відтінок із квітковим мотивом створює ніжний, елегантний образ — чудово і як подарунок.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('newborn-bunny-set', 170, 'baby', 239, null, 4.9, 38, '🐇', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["0-3m"]'::jsonb, '["0-6m"]'::jsonb, '[{"name": "Pink", "hex": "#f4b9c8", "images": ["/products/newborn-bunny-set/pink-1.jpg", "/products/newborn-bunny-set/pink-2.jpg", "/products/newborn-bunny-set/pink-3.jpg", "/products/newborn-bunny-set/pink-4.jpg", "/products/newborn-bunny-set/pink-5.jpg"]}, {"name": "Beige", "hex": "#e6d3b8", "images": ["/products/newborn-bunny-set/beige-1.jpg", "/products/newborn-bunny-set/beige-2.jpg", "/products/newborn-bunny-set/beige-3.jpg", "/products/newborn-bunny-set/beige-4.jpg", "/products/newborn-bunny-set/beige-5.jpg"]}, {"name": "Peach", "hex": "#f8c8b0", "images": ["/products/newborn-bunny-set/peach-1.jpg", "/products/newborn-bunny-set/peach-2.jpg"]}]'::jsonb, null, false, true, false, false, false, true, 'Novorozenecká souprava se zajíčkem', 'Newborn Bunny 3-Piece Set', 'Комплект для новонароджених із зайчиком', 'Roztomilá 3dílná souprava pro novorozence, která zajistí miminku maximální pohodlí od prvních dnů života. Komplet obsahuje kabátek s dlouhým rukávem, polodupačky a čepičku. Motiv zajíčka s medvídkem je ideální jako první výbavička nebo dárek.', 'A sweet newborn 3-piece set that keeps baby comfortable from day one: a long-sleeve jacket, footed pants and a matching hat. The bunny-and-teddy motif makes it a perfect first outfit or newborn gift.', 'Милий комплект із 3 частин для новонароджених, що дарує малюку комфорт із перших днів життя: кофтинка з довгим рукавом, повзунки та шапочка. Мотив зайчика з ведмедиком — ідеально як перший гардероб чи подарунок.', '100 % bavlna, šetrná k citlivé pokožce novorozence', '100% cotton, gentle on newborn skin', '100 % бавовна, дбайлива до шкіри новонародженого'),
('newborn-bear-set', 180, 'baby', 209, null, 4.8, 27, '🧸', 'linear-gradient(140deg, #ffe3ec 0%, #ffc9d8 60%, #ffb6c8 100%)', '["50", "56", "62"]'::jsonb, '["0-6m"]'::jsonb, '[{"name": "Pink", "hex": "#f4b9c8", "images": ["/products/newborn-bear-set/pink-1.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Novorozenecká souprava s medvídkem', 'Newborn Bear 2-Piece Set', 'Комплект для новонароджених із ведмедиком', 'Jemná 2dílná souprava pro novorozené holčičky. Komplet obsahuje praktický overal se zapínáním na patentky po celé délce a měkkou čepičku. Jemná růžová barva s roztomilým motivem medvídka se hvězdičkami.', 'A gentle two-piece set for newborn girls: a practical overall with full-length snap buttons and a soft matching hat. The teddy-bear-and-stars motif in soft pink makes dressing and changing easy and adorable.', null, '100 % bavlna, šetrná k citlivé pokožce novorozence', '100% cotton, gentle on newborn skin', '100 % бавовна, дбайлива до шкіри новонародженого'),
('animal-romper', 190, 'baby', 169, null, 4.8, 45, '🦁', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["0-3m", "3-6m", "6-9m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Cream", "hex": "#f2ead9", "images": ["/products/animal-romper/cream-1.jpg", "/products/animal-romper/cream-2.jpg", "/products/animal-romper/cream-3.jpg", "/products/animal-romper/cream-4.jpg", "/products/animal-romper/cream-5.jpg"]}]'::jsonb, 'Bestseller', false, true, false, false, false, true, 'Dětský overal se zvířátky', 'Animal Baby Romper', 'Дитячий чоловічок зі звірятками', 'Měkký a pohodlný overal pro miminka z kvalitní žebrované bavlny. Díky praktickému zapínání na patentky po celé délce se snadno obléká i přebaluje. Roztomilé motivy zvířátek – lvíčci, medvídci i Winnie – jsou ideální pro každodenní nošení i spaní.', 'A soft ribbed-cotton romper with full-length snap buttons for easy dressing and changing. Available with several adorable animal motifs — lion cubs, teddy bears and Winnie — ideal for playtime, sleep or gifting.', null, '100 % žebrovaná bavlna, měkká a prodyšná', '100% ribbed cotton, soft and breathable', null),
('boys-romper-hat', 200, 'baby', 249, null, 4.8, 33, '💚', 'linear-gradient(140deg, #e2f5e4 0%, #cdeccd 60%, #b5e0b8 100%)', '["0-3m", "3-6m", "6-9m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Green", "hex": "#a8c4a0", "images": ["/products/boys-romper-hat/green-1.jpg", "/products/boys-romper-hat/green-2.jpg", "/products/boys-romper-hat/green-3.jpg", "/products/boys-romper-hat/green-4.jpg", "/products/boys-romper-hat/green-5.jpg"]}, {"name": "Blue", "hex": "#a9c8ea", "images": ["/products/boys-romper-hat/blue-1.jpg"]}, {"name": "Greige", "hex": "#cfc5b8", "images": ["/products/boys-romper-hat/greige-1.jpg"]}]'::jsonb, null, false, true, false, false, false, true, 'Chlapecký overal s čepičkou', 'Boys Romper with Hat', 'Чоловічок для хлопчика із шапочкою', 'Pohodlný a stylový komplet pro miminka: bavlněný overal se špičkou a dlouhým rukávem a sladěná čepička. Praktické zapínání na patentky po celé délce usnadňuje oblékání i přebalování. Dostupný v zelené, světle modré a šedo-béžové.', 'A comfy baby set with a long-sleeve footed romper and matching hat. Full-length snap buttons make dressing and changing simple, and the gentle teddy-bear motif keeps it cute. In green, light blue and grey-beige.', 'Зручний комплект для малюків: бавовняний чоловічок із закритими ніжками та довгим рукавом і шапочка в тон. Кнопки по всій довжині полегшують одягання. У зеленому, блакитному та сіро-бежевому кольорах.', '100 % bavlna, šetrná k citlivé dětské pokožce', '100% cotton, gentle on sensitive skin', '100 % бавовна, дбайлива до чутливої шкіри'),
('tiger-3piece-set', 210, 'baby', 249, null, 4.7, 18, '🐯', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["3-6m", "6-9m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Beige", "hex": "#e0cdb0", "images": ["/products/tiger-3piece-set/beige-1.jpg", "/products/tiger-3piece-set/beige-2.jpg", "/products/tiger-3piece-set/beige-3.jpg", "/products/tiger-3piece-set/beige-4.jpg", "/products/tiger-3piece-set/beige-5.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Chlapecká 3dílná souprava s tygříkem', 'Tiger 3-Piece Baby Set', 'Комплект із тигреням (3 частини)', 'Roztomilá a pohodlná 3dílná souprava pro malé dobrodruhy. Komplet obsahuje body s dlouhým rukávem, pohodlné kalhoty a sladěnou čepičku. Veselý motiv tygříka a moderní zvířecí vzor dodávají soupravě originální vzhled.', 'An adorable 3-piece set for little adventurers: a long-sleeve bodysuit, comfy pants and a matching hat. The cheerful tiger motif and modern animal print give the outfit an original look.', 'Чарівний комплект із 3 частин для маленьких дослідників: боді з довгим рукавом, зручні штани та шапочка в тон. Веселе тигреня та сучасний анімалістичний принт.', '100 % bavlna, šetrná k citlivé dětské pokožce', '100% cotton, gentle on sensitive skin', '100 % бавовна, дбайлива до чутливої шкіри'),
('hearts-skirt-set', 220, 'girls', 389, null, 4.9, 23, '❤️', 'linear-gradient(140deg, #ffe0e0 0%, #ffc4c4 60%, #ffabab 100%)', '["3-6m", "6-9m", "9-12m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Red", "hex": "#d94f4f", "images": ["/products/hearts-skirt-set/red-1.jpg", "/products/hearts-skirt-set/red-2.jpg", "/products/hearts-skirt-set/red-3.jpg", "/products/hearts-skirt-set/red-4.jpg", "/products/hearts-skirt-set/red-5.jpg"]}]'::jsonb, 'New', true, false, false, true, false, true, 'Dívčí souprava se srdíčky a sukýnkou', 'Hearts Skirt 3-Piece Set', 'Комплект зі спідничкою та сердечками (3 частини)', 'Elegantní a roztomilá 3dílná souprava pro malé princezny. Komplet obsahuje body s dlouhým rukávem, stylovou sukýnku s velkou mašlí a sladěnou čelenku. Jemný vzor červených srdíček je ideální na oslavy, focení i každodenní nošení.', 'An elegant 3-piece set for little princesses: a long-sleeve bodysuit with ruffles, a red skirt with a big decorative bow and a matching headband. The delicate red-hearts print makes it perfect for celebrations and photo shoots.', 'Елегантний комплект із 3 частин для маленьких принцес: боді з довгим рукавом і рюшами, червона спідничка з великим бантом та повʼязка в тон. Ніжний принт із сердечками — ідеально для свят і фотосесій.', '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('hearts-3piece-set', 230, 'girls', 329, null, 4.8, 15, '💕', 'linear-gradient(140deg, #ffe0e0 0%, #ffc4c4 60%, #ffabab 100%)', '["3-6m", "6-9m", "9-12m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Red", "hex": "#d94f4f", "images": ["/products/hearts-3piece-set/red-1.jpg", "/products/hearts-3piece-set/red-2.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Dívčí 3dílná souprava se srdíčky', 'Hearts 3-Piece Set', 'Комплект із сердечками (3 частини)', 'Stylová a pohodlná 3dílná souprava pro malé princezny. Komplet obsahuje body s dlouhým rukávem, pohodlné kalhoty a mikinu s kapucí zdobenou motivem srdíček a mašlí. Moderní kombinace červené a smetanové barvy s jemným žebrovaným vzorem.', 'A stylish 3-piece set for little princesses: a long-sleeve bodysuit, comfy pants and a hooded sweatshirt with a hearts motif and a bow on the hood. A modern red-and-cream combination with a fine ribbed texture.', null, '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null),
('fox-romper-set', 240, 'baby', 449, null, 4.9, 20, '🦊', 'linear-gradient(140deg, #ffeadd 0%, #ffd8c2 60%, #ffc9ad 100%)', '["0-3m", "3-6m"]'::jsonb, '["0-6m"]'::jsonb, '[{"name": "Pink", "hex": "#f4b9c8", "images": ["/products/fox-romper-set/pink-1.jpg"]}, {"name": "Blue", "hex": "#a9c8ea", "images": ["/products/fox-romper-set/blue-1.jpg"]}]'::jsonb, null, false, false, false, false, false, true, 'Dívčí souprava s liškou', 'Fox Romper Set', 'Комплект із лисичкою', 'Něžná a elegantní souprava pro malé princezny. Komplet obsahuje pohodlný overal s dlouhým rukávem a sladěnou čelenku nebo čepičku. Romantický motiv lišky a květin je ideální pro první společné chvíle i slavnostní příležitosti.', 'A tender, elegant set for little princesses: a comfy long-sleeve overall with a matching headband or hat, decorated with a romantic fox embroidery and flowers. Ideal for first outings and special occasions.', 'Ніжний та елегантний комплект для маленьких принцес: зручний чоловічок із довгим рукавом і повʼязка або шапочка в тон. Романтична вишивка лисички та квіти — для перших прогулянок і особливих моментів.', '100 % bavlna, šetrná k citlivé dětské pokožce', '100% cotton, gentle on sensitive skin', '100 % бавовна, дбайлива до чутливої шкіри'),
('ribbed-romper-set', 250, 'baby', 249, null, 4.8, 31, '🎀', 'linear-gradient(140deg, #f7eede 0%, #efe0c8 60%, #e6d2b2 100%)', '["0-3m", "3-6m", "6-9m", "9-12m"]'::jsonb, '["0-6m", "6-12m"]'::jsonb, '[{"name": "Beige", "hex": "#e3d2b8", "images": ["/products/ribbed-romper-set/beige-1.jpg", "/products/ribbed-romper-set/beige-2.jpg", "/products/ribbed-romper-set/beige-3.jpg", "/products/ribbed-romper-set/beige-4.jpg", "/products/ribbed-romper-set/beige-5.jpg"]}, {"name": "Dark Green", "hex": "#4e6b52", "images": ["/products/ribbed-romper-set/darkgreen-1.jpg"]}]'::jsonb, 'Bestseller', false, true, false, true, false, true, 'Dívčí žebrovaný overal s čelenkou', 'Ribbed Romper & Headband', 'Чоловічок у рубчик із повʼязкою', 'Stylový a pohodlný komplet pro malé princezny: měkký žebrovaný overal s dlouhým rukávem a sladěná čelenka s mašlí. Elegantní volánky na ramenou a ozdobná mašle dodávají outfitu jemný a moderní vzhled. V béžové a tmavě zelené barvě.', 'A stylish set for little princesses: a soft ribbed long-sleeve romper with a matching bow headband. Elegant shoulder ruffles and a front bow add a modern touch; snap buttons make changing easy. In beige and dark green.', null, '100 % žebrovaná bavlna, měkká a prodyšná', '100% ribbed cotton, soft and breathable', null),
('elegant-romper', 260, 'baby', 289, null, 4.9, 14, '✨', 'linear-gradient(140deg, #efe8ff 0%, #ded1ff 60%, #cbbcf5 100%)', '["0-3m", "3-6m", "6-9m"]'::jsonb, '["0-6m"]'::jsonb, '[{"name": "Pink", "hex": "#f4b9c8", "images": ["/products/elegant-romper/pink-1.jpg"]}]'::jsonb, 'New', false, false, true, true, false, true, 'Dívčí elegantní overal', 'Elegant Girls Romper', 'Елегантний чоловічок для дівчинки', 'Jemný a elegantní overal, který spojuje pohodlí s krásným slavnostním vzhledem. Kombinace měkké bavlny, ozdobného límečku, mašličky v pase a třpytivých růžových kalhot je ideální pro výjimečné příležitosti i každodenní nošení.', 'A delicate, elegant romper that combines comfort with a festive look: soft cotton, a decorative collar, a bow at the waist and subtly sparkly pink trousers. Ideal for celebrations, photo shoots and gifting.', null, '100 % bavlna, měkká a prodyšná', '100% cotton, soft and breathable', null)
on conflict (id) do nothing;
